### ISSUE TITLE
not an issue but is a domain whitelist really that small?

### ISSUE THREAD

**Issue by jawz101** [cbuijs/accomplist#1]
Seems like an aggregated whitelist from all of those blacklists would have a lot more than 20 or so domains.

Also, have you heard of these tools?

[grepcidr](http://www.pc-tools.net/unix/grepcidr/)
[aggregate-cidr-addresses](https://zwitterion.org/software/aggregate-cidr-addresses/)
[PyFunceble](https://github.com/funilrys/PyFunceble)

**Comment by cbuijs** [comment]
The whitelist is cleaned of entries that are not blacklisted and vice
versa. In general the whitelist should be empty except of some forced
entries due to blocking based on responses (e.g. up addressed that are
blocked).

In short: no need to whitelist anything if it is not blacklisted.

That said. The "plain" version are full fletched. Just not combined.

Hope this clears things up.

**Comment by jawz101** [comment]
thanks.  I just figured there would surely be more false positives amongst so many sources
