### ISSUE TITLE
Which list must I use

### ISSUE THREAD

**Issue by pallebone** [cbuijs/accomplist#1]
Hi there,

Thanks for your work :)

Its not clear to me what is the aggregated list, after reading the readme. Which list/file contains all the aggregated domains I can use to add to my blocker?

Kind regards
Pete

**Comment by cbuijs** [comment]
Sorry for late response ...

Which blocker do you use?

**Comment by pallebone** [comment]
Hello. I use pihole. As you had not replied I guessed and used the /deugniet/plain.black.domain.list and /malicious-dom/plain.black.domain.list.

P

**Comment by cbuijs** [comment]
That works :-)

I suggest the following combination (from experience and use it myself):

**nrd/plain.black.top-n.domain.list** (Newly registered domains, younger then 30 days)
**oisd/plain.black.top-n.domain.list** (My optimized version of https://oisd.nl)
**family-safe/plain.black.top-n.domain.list** (Adult/Illegal themed domains)

Last one is more to protect youngsters against adult/gambling/illegal/etc stuff. When not needed, the first two do a great job against ads/trackers/malware/etc...

The "top-n" versions are actually only containing domains that are actually ACTIVE and USED. Most of the lists have very old domains that pilled-up historically and are very large and memory hungry. The Top-N lists have the same efficiency as the larger ones (I test this regularly), but without the bloat. I highly recommend them. Otherwise use the same files without "top-n" in them.

Enjoy :-).

**Comment by pallebone** [comment]
Thank you. 

Based on this I have added the suggestion above.

Can I ask what deugniets list is for then? I have left that one in, I saw that was your recommended on on the readme?

Pete

**Comment by cbuijs** [comment]
Deugniets was/is used together with my [filtering DNS forwarder](https://github.com/cbuijs/deugniets), it has some specific stuff in there. You don't have to include it, as the suggested lists above overlap it.

**Comment by pallebone** [comment]
Many thanks.
