### ISSUE TITLE
False positive domain gstaticadssl.l.google.com

### ISSUE THREAD

**Issue by charlieporth1** [cbuijs/accomplist#2]
You have a false positive domain `gstaticadssl.l.google.com` in the [this file](https://github.com/cbuijs/accomplist/blob/master/chris/google-black.list#L41)
This domain has fooled many people too. It's on [Reddit](https://www.reddit.com/r/pihole/comments/hbmrc3/gstaticadssllgooglecom_is_blocked_a_lot_but_shows/) for the Pi-Hole community. 
A quick `dig fonts.gstatic.com` will tell you that `gstaticadssl.l.google.com` is the `A` record for  the `CNAME` of `fonts.gstatic.com`

**Comment by cbuijs** [comment]
Just seeing this after 7 months (blush).

What breaks when this is used in a blocklist?

`fonts.gstatic.com` is notorious for ads and tracking and is kind of misleading by name because of it.

Just add it to your allowlist if it gives you problems? Or use this list as a allowlist instead of a blocklist?

(using it forever already and do not experience any breakage on my usage).
