### ISSUE TITLE
google-doms missing?

### ISSUE THREAD

**Issue by ignoramous** [cbuijs/accomplist#4]
Hi,

*rethinkdns dev here*; we use a some of your lists, so thanks for your work (:

For the past week or so, download for [accomplist/chris/google-doms.list](https://raw.githubusercontent.com/cbuijs/accomplist/master/chris/google-doms.list) has been failing. Can you please check (assuming this list is still supported)?

**Comment by cbuijs** [comment]
Ah... thanks for that (and sorry for belated response). And you are welcome! ;-). Thanks for RethinkDNS as well! Awesome!

I changed some stuff to make sure that only google tracking/etc stuff is blocked, these are [here](https://github.com/cbuijs/accomplist/tree/master/google). The point of the new one is not to "break" google, but only block the tracking/ads and such.

I can/will reiterate the google-doms.list one, the process of gathering still runs, but the file is not updated anymore because of the changes I made to generate above. Give me a week or so to fix, as I am on travel and have no access to my compute resources at the moment.
